### PR TITLE
Rollback dispatch patch

### LINKED ISSUE #601: NMS CPU extension does not compile with pytorch 1.0.1 / nightly
## 🐛 Bug

A compilation error is thrown when building with the latest version of pytorch or pytorch-nightly

## To Reproduce

`nvidia-docker build -t maskrcnn-benchmark docker/`

## Expected behavior

maskrcnn-benchmark should build correctly

## Environment

 - Docker

## Additional context

```
building 'maskrcnn_benchmark._C' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/maskrcnn-benchmark
creating build/temp.linux-x86_64-3.6/maskrcnn-benchmark/maskrcnn_benchmark
creating build/temp.linux-x86_64-3.6/maskrcnn-benchmark/maskrcnn_benchmark/csrc
creating build/temp.linux-x86_64-3.6/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu
creating build/temp.linux-x86_64-3.6/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda
gcc -pthread -B /miniconda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/csrc/api/include -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/TH -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/THC -I/usr/local/cuda/include -I/miniconda/envs/py36/include/python3.6m -c /maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
gcc -pthread -B /miniconda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/csrc/api/include -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/TH -I/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/THC -I/usr/local/cuda/include -I/miniconda/envs/py36/include/python3.6m -c /maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp -o build/temp.linux-x86_64-3.6/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/ATen/ATen.h:9:0,
                 from /miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
                 from /miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/csrc/api/include/torch/data.h:3,
                 from /miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/csrc/api/include/torch/all.h:4,
                 from /miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/torch/extension.h:4,
                 from /maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/vision.h:3,
                 from /maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp:2:
/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp: In lambda function:
/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp:71:46: error: invalid initialization of reference of type 'const at::Type&' from expression of type 'c10::ScalarType'
   AT_DISPATCH_FLOATING_TYPES(dets.scalar_type(), "nms", [&] {
                                              ^
/miniconda/envs/py36/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro 'AT_DISPATCH_FLOATING_TYPES'
     const at::Type& the_type = TYPE;                                         \
                                ^
error: command 'gcc' failed with exit status 1

```

### PR DESCRIPTION
**Pull request by miguelvr**
Reverts AT_DISPATCH_FLOATING_TYPES patch, which lead to a compilation error with the latest version of pytorch and pytorch-nightly

FIxes #601

### CODE REVIEW

**Comment by miguelvr** [comment]
cc @fmassa

**Comment by fmassa** [comment]
cc @vishwakftw I believe this can be reverted now, given that there was a backward-compatibility fix sent to PyTorch?

**Comment by fmassa** [comment]
Also note that this will be introducing deprecation warnings during compilation time https://github.com/pytorch/pytorch/pull/17996
